Feature extraction using LLm

In [1]:
!pip install groq

Requirement already satisfied: groq in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (0.37.1)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (2.11.9)
Requirement already satisfied: sniffio in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from groq) (4.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from anyio<5,>=3.5.0->groq) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: certifi in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from httpx<1,>=0.23.0->groq) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from pydantic<3,>=1.9.0->groq) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\farah\anaconda3\envs\fixed-env\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.1)

In [5]:
import llm_feature_extraction as feature_extraction
import os
import pandas as pd

In [20]:
# Dynamically determine the base directory
script_dir = os.path.dirname(os.getcwd())  # Directory where script is located
base_dir = os.path.dirname(script_dir)  # Go up one level
file_path = os.path.join(base_dir, "Scrapping.module", "Tayara.tn", "clean_rawData", "tayara_listings_agregated.csv")

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("File loaded, shape:", df.shape)
else:
    print("File not found at:", os.path.abspath(file_path))

File loaded, shape: (2502, 10)

In [21]:
df.head()

,Unnamed: 0,id,categorie,date,gouvernorat,delegation,prix,titre,description,neuf
0,0,693c50e8cd04d08be749ee7a,appartements,2025-12-14 17:32:53+00:00,Tunis,Gammarth,270000,un appartement s+2,"Appartement S+2 sur la route du Relais, dans ...",False
1,1,693ef21fcd04d08be74add4e,appartements,2025-12-14 17:21:35+00:00,Monastir,Bekalta,140000,Apparemment meublé sousse s+2,Je mets en vente cette appartement s+2 90 m2\n...,False
2,2,692b30e3145e1617cbae0a19,appartements,2025-12-14 17:18:54+00:00,Monastir,Monastir,250000,Bel appartement S+2 proche de la plage Palmier,À VENDRE – Bel appartement S+2 proche de la pl...,False
3,3,68ced66b516f1ddb82deec8b,appartements,2025-12-14 17:15:55+00:00,Monastir,Monastir,270000,Appartement S+2 Vue Mer,immobilière ajina vous propose :\n\nÀ VENDRE –...,False
4,4,6835f44f1539f905891f465b,appartements,2025-12-14 17:04:54+00:00,Nabeul,Hammam Ghezèze,205000,Appartements Haut standing en cours de constr...,A vendre des appartements Haut standing en co...,False

In [14]:
import importlib
importlib.reload(feature_extraction)
feature_extraction.traiter_annonces(df,"description")

✓ Annonce 693c50e8cd04d08be749ee7a déjà traitée
✓ Annonce 693ef21fcd04d08be74add4e déjà traitée
✓ Annonce 692b30e3145e1617cbae0a19 déjà traitée
✓ Annonce 68ced66b516f1ddb82deec8b déjà traitée
✓ Annonce 6835f44f1539f905891f465b déjà traitée
✓ Annonce 69241d53265523b710eab18f déjà traitée
✓ Annonce 68cd8842516f1ddb82de201f déjà traitée
✓ Annonce 68ff498388bfe5662475cd42 déjà traitée
✓ Annonce 69330f76cd04d08be745f723 déjà traitée
✓ Annonce 691b5059265523b710e6a6b7 déjà traitée
✓ Annonce 68ffa297d0d95991e106335f déjà traitée
✓ Annonce 6915cdde145e1617cba4c5f7 déjà traitée
✓ Annonce 68ffa29ab756576ab409e0f9 déjà traitée
✓ Annonce 68c5824171554c2d1b317b76 déjà traitée
✓ Annonce 693c2a9acd04d08be749d6bc déjà traitée
✓ Annonce 68c840ff07c7711d7c6d596f déjà traitée
✓ Annonce 6808bd04c1f8f57898dfc503 déjà traitée
✓ Annonce 691740eb145e1617cba58f52 déjà traitée
✓ Annonce 693c29c9cd04d08be749d633 déjà traitée
✓ Annonce 6917400e145e1617cba58ea2 déjà traitée
✓ Annonce 691e1f24265523b710e7e8cd déjà traitée
✓ Annonce 68f78f2cb756576ab405814c déjà traitée
✓ Annonce 68beec4bc4782c5427ae85d6 déjà traitée
✓ Annonce 6937f1ef8914daae519869b3 déjà traitée
✓ Annonce 6900c305b756576ab40a7dd5 déjà traitée
✓ Annonce 685aa69dd5464a896c9a10a9 déjà traitée
✓ Annonce 68d27a2c07c7711d7c73a40a déjà traitée
✓ Annonce 693ea68a8914daae519b2dca déjà traitée
✓ Annonce 693ea03ccd04d08be74ab546 déjà traitée
✓ Annonce 6939ace0cd04d08be748c873 déjà traitée
✓ Annonce 693a90cf8914daae51998def déjà traitée
✓ Annonce 693e9d8bcd04d08be74ab400 déjà traitée
✓ Annonce 6939a7cecd04d08be748c561 déjà traitée
✓ Annonce 693a8efe8914daae51998cd4 déjà traitée
✓ Annonce 6939a5ffcd04d08be748c449 déjà traitée
✓ Annonce 69399ba68914daae5199356c déjà traitée
✓ Annonce 6939a0d9cd04d08be748c187 déjà traitée
✓ Annonce 6939976bcd04d08be748bc0f déjà traitée
✓ Annonce 693998dfcd04d08be748bd1a déjà traitée
✓ Annonce 693a8ca4cd04d08be749159f déjà traitée
✓ Annonce 6925cdd3265523b710eb5552 déjà traitée
✓ Annonce 684bfbaa92753d6d79af8d08 déjà traitée
✓ Annonce 6904c2146490817594e077fc déjà traitée
✓ Annonce 6904c1338e4e0e4acb5a3b57 déjà traitée
✓ Annonce 689f17737e1ff28d3ad464fa déjà traitée
✓ Annonce 691b3037145e1617cba76502 déjà traitée
✓ Annonce 693bf089cd04d08be749b287 déjà traitée
✓ Annonce 6939ae1fcd04d08be748c964 déjà traitée
✓ Annonce 6939aac6cd04d08be748c71c déjà traitée
✓ Annonce 68a702ad3398639ecd911068 déjà traitée
✓ Annonce 68f600cbd0d95991e100ea99 déjà traitée
✓ Annonce 693e8a2c8914daae519b2155 déjà traitée
✓ Annonce 6920415c265523b710e8e525 déjà traitée
✓ Annonce 6933ec6fcd04d08be7463ed7 déjà traitée
✓ Annonce 6880a5fad5464a896cb3f75e déjà traitée
✓ Annonce 68f7492dd0d95991e1019b87 déjà traitée
✓ Annonce 6909e3746490817594e33e5d déjà traitée
✓ Annonce 690dcc00145e1617cb9e7be3 déjà traitée
✓ Annonce 68f0eef33e7ffb8ac15c56f2 déjà traitée
✓ Annonce 693aa377cd04d08be74923f9 déjà traitée
✓ Annonce 6932be37cd04d08be745c7f1 déjà traitée
✓ Annonce 693d36cbcd04d08be74a366c déjà traitée
✓ Annonce 69368f6acd04d08be7473ff8 déjà traitée
✓ Annonce 68d7c09507c7711d7c76d7d9 déjà traitée
✓ Annonce 693e4dae8914daae519b11cc déjà traitée
✓ Annonce 693e4d73cd04d08be74a9c5a déjà traitée
✓ Annonce 682c8f456238a0abfdd3b7a2 déjà traitée
✓ Annonce 693dd0748914daae519af705 déjà traitée
✓ Annonce 693a8f968914daae51998d2d déjà traitée
✓ Annonce 693a91ed8914daae51998e8d déjà traitée
✓ Annonce 69282794265523b710ec12e4 déjà traitée
✓ Annonce 692b1e25265523b710ed2ccc déjà traitée
✓ Annonce 67f9504dfd1c6385be4bf219 déjà traitée
✓ Annonce 693d79368914daae519ac951 déjà traitée
✓ Annonce 693d7904cd04d08be74a53a7 déjà traitée
✓ Annonce 693d7866cd04d08be74a536a déjà traitée
✓ Annonce 693d783ccd04d08be74a5359 déjà traitée
✓ Annonce 68d112db27f44446941154fe déjà traitée
✓ Annonce 69317e65265523b710ef9909 déjà traitée
✓ Annonce 68cd6d7407c7711d7c708599 déjà traitée
✓ Annonce 68d112c407c7711d7c72b2dd déjà traitée
✓ Annonce 693d75b8cd04d08be74a5240 déjà traitée
✓ Annonce 693d759ecd04d08be74a522d déjà traitée
✓ Annonce 693d74f7cd04d08be74a51da déjà traitée
✓ Annonce 693d74c68914daae519ac775 déjà traitée
✓ Annonce 693d746acd04d08be74a519d déjà traitée
✓ Annonce 693d735ecd04d08be74a511b déjà traitée
✓ Annonce 693d7359cd04d08be74a511a déjà traitée
✓ Annonce 693d7331cd04d08be74a5105 déjà traitée
✓ Annonce 693d73198914daae519ac6b1 déjà traitée
✓ Annonce 693d72d4cd04d08be74a50e1 déjà traitée
✓ Annonce 693d72be8914daae519ac671 déjà traitée
✓ Annonce 693d72aecd04d08be74a50ce déjà traitée
✓ Annonce 693d728acd04d08be74a50bc déjà traitée
✓ Annonce 693d72548914daae519ac629 déjà traitée
✓ Annonce 693d72228914daae519ac611 déjà traitée
✓ Annonce 693d720a8914daae519ac5fb déjà traitée
✓ Annonce 693d71f4cd04d08be74a506d déjà traitée
✓ Annonce 693d71a5cd04d08be74a503f déjà traitée
✓ Annonce 693d7195cd04d08be74a5035 déjà traitée
✓ Annonce 693d716a8914daae519ac59b déjà traitée
✓ Annonce 693d71468914daae519ac583 déjà traitée
✓ Annonce 693d712e8914daae519ac578 déjà traitée
✓ Annonce 693d711ccd04d08be74a4ffd déjà traitée
✓ Annonce 693d710dcd04d08be74a4ff5 déjà traitée
✓ Annonce 693d70d48914daae519ac546 déjà traitée
✓ Annonce 693d70c38914daae519ac53c déjà traitée
✓ Annonce 693d7086cd04d08be74a4fb7 déjà traitée
✓ Annonce 693d7071cd04d08be74a4fa8 déjà traitée
✓ Annonce 693d70428914daae519ac4fe déjà traitée
✓ Annonce 693d6a27cd04d08be74a4ccc déjà traitée
✓ Annonce 690878f28e4e0e4acb5c24d0 déjà traitée
✓ Annonce 6865430294cd0376dcd3634d déjà traitée
✓ Annonce 693d5abf8914daae519abbcb déjà traitée
✓ Annonce 68e66c38e7035d31a41242e9 déjà traitée
✓ Annonce 68c13f0ac4782c5427afe4b5 déjà traitée
✓ Annonce 693d5a16cd04d08be74a45b7 déjà traitée
✓ Annonce 693d597b8914daae519abb2a déjà traitée
✓ Annonce 693d590acd04d08be74a4558 déjà traitée
✓ Annonce 68cbd1b307c7711d7c6f6e83 déjà traitée
✓ Annonce 693d509f8914daae519ab747 déjà traitée
✓ Annonce 693016d4265523b710ef0417 déjà traitée
✓ Annonce 6932c213cd04d08be745ca5b déjà traitée
✓ Annonce 693855fb8914daae5198b0f3 déjà traitée
✓ Annonce 692ade1f145e1617cbade6e8 déjà traitée
✓ Annonce 68adbe62032c2f2572191798 déjà traitée
✓ Annonce 69035e95b756576ab40bee7a déjà traitée
✓ Annonce 683599c4cf58eeced24722d5 déjà traitée
✓ Annonce 67b5faf686d5f7a45c1e9feb déjà traitée
✓ Annonce 68dfd3ea6c505afdc05d5d82 déjà traitée
✓ Annonce 693d3ea58914daae519aaf11 déjà traitée
✓ Annonce 682c6d1341532c94f15d90f6 déjà traitée
✓ Annonce 6749d36a0d8480a1e01a20d3 déjà traitée
✓ Annonce 693d3aee8914daae519aad6e déjà traitée
✓ Annonce 693d3a83e709fbd3ac2f1813 déjà traitée
✓ Annonce 693d393e8914daae519aace7 déjà traitée
✓ Annonce 693d38c2cd04d08be74a377f déjà traitée
✓ Annonce 693d388b8914daae519aac9f déjà traitée
✓ Annonce 693d36e8cd04d08be74a367b déjà traitée
✓ Annonce 6894731f4ad00efe973ad889 déjà traitée
✓ Annonce 68c95c3012d0d5ef5cfba55b déjà traitée
✓ Annonce 69185fb8145e1617cba61301 déjà traitée
✓ Annonce 678effa9bdc42e9182e1da89 déjà traitée
✓ Annonce 692dc5b6145e1617cbaee5ce déjà traitée
✓ Annonce 678046c9f39faeaa98cd807c déjà traitée
✓ Annonce 68f605c66bcfa867f54df41e déjà traitée
✓ Annonce 68e3bf7de7035d31a4109a65 déjà traitée
✓ Annonce 6813e307c1f8f57898e74ea4 déjà traitée
✓ Annonce 676c706db7de28167ec6e20b déjà traitée
✓ Annonce 67edc7dcca3467b14e727bf0 déjà traitée
✓ Annonce 6930585d145e1617cbaffdde déjà traitée
✓ Annonce 693d30fbcd04d08be74a341a déjà traitée
✓ Annonce 693d30d8cd04d08be74a3408 déjà traitée
✓ Annonce 6893be01fde7ee723b463380 déjà traitée
✓ Annonce 68d7063e516f1ddb82e40826 déjà traitée
✓ Annonce 68c5825671554c2d1b317b89 déjà traitée
✓ Annonce 68f623f9d0d95991e10100db déjà traitée
✓ Annonce 690f30dc145e1617cb9fea14 déjà traitée
✓ Annonce 68f39452b756576ab403528d déjà traitée
✓ Annonce 68ed0623ebd8d75bc802a198 déjà traitée
✓ Annonce 68b5cac4711369bbe4f5e64c déjà traitée
✓ Annonce 692431fdda5d3acb89b32ef1 déjà traitée
✓ Annonce 68e913513e7ffb8ac157f3a2 déjà traitée
✓ Annonce 693d29288914daae519aa5af déjà traitée
✓ Annonce 69353f06cd04d08be746c12d déjà traitée
✓ Annonce 693d27d48914daae519aa51c déjà traitée
✓ Annonce 693d25b48914daae519aa40c déjà traitée
✓ Annonce 693d24d68914daae519aa3a9 déjà traitée
✓ Annonce 693d2483cd04d08be74a2ea4 déjà traitée
✓ Annonce 673debf03c20a99fb554c5df déjà traitée
✓ Annonce 693d23d1cd04d08be74a2e39 déjà traitée
✓ Annonce 6883a58cd69a89221d3c1b01 déjà traitée
✓ Annonce 69285482265523b710ec262a déjà traitée
✓ Annonce 693d20e08914daae519aa1c7 déjà traitée
✓ Annonce 693d20638914daae519aa179 déjà traitée
✓ Annonce 693d2050cd04d08be74a2c4c déjà traitée
✓ Annonce 693d20368914daae519aa159 déjà traitée
✓ Annonce 693d1ffbcd04d08be74a2c1a déjà traitée
✓ Annonce 693d1fc5cd04d08be74a2bfb déjà traitée
✓ Annonce 693d1fb1cd04d08be74a2bed déjà traitée
✓ Annonce 693d1f2bcd04d08be74a2bbc déjà traitée
✓ Annonce 693d1eee8914daae519aa0c1 déjà traitée
✓ Annonce 693d1ec6cd04d08be74a2b7f déjà traitée
✓ Annonce 693990a6cd04d08be748b829 déjà traitée
✓ Annonce 6936e5ec26d7926c8bc4f2a6 déjà traitée
✓ Annonce 690f40aa145e1617cb9ffc5f déjà traitée
✓ Annonce 693d170fcd04d08be74a286f déjà traitée
✓ Annonce 69304e89145e1617cbaff7fb déjà traitée
✓ Annonce 693c63688914daae519a6dd0 déjà traitée
✓ Annonce 693c5c74cd04d08be749f50d déjà traitée
✓ Annonce 693c59e0cd04d08be749f3b2 déjà traitée
✓ Annonce 693c59988914daae519a6836 déjà traitée
✓ Annonce 680220fbc5beda2b51c9133b déjà traitée
✓ Annonce 693c44d0cd04d08be749e76d déjà traitée
✓ Annonce 693c3d94cd04d08be749e329 déjà traitée
✓ Annonce 693c3b4c8914daae519a5683 déjà traitée
✓ Annonce 68c83ddb07c7711d7c6d5739 déjà traitée
✓ Annonce 693c36becd04d08be749defe déjà traitée
✓ Annonce 68de60d16c505afdc05c8bc1 déjà traitée
✓ Annonce 693c35f68914daae519a5305 déjà traitée
✓ Annonce 674aecd83c20a99fb55c2ba3 déjà traitée
✓ Annonce 68e4d3626c505afdc06026ce déjà traitée
✓ Annonce 693c31eb8914daae519a503b déjà traitée
✓ Annonce 693c2ced8914daae519a4cc6 déjà traitée
✓ Annonce 693c2a7bcd04d08be749d6a6 déjà traitée
✓ Annonce 693993c2cd04d08be748b9dd déjà traitée
✓ Annonce 68c56161e33e2deec930b99c déjà traitée
✓ Annonce 687e396794cd0376dce4a5a6 déjà traitée
✓ Annonce 6908b5096490817594e2918f déjà traitée
✓ Annonce 68c56081e33e2deec930b8ec déjà traitée
✓ Annonce 68fb8265b756576ab407b9b9 déjà traitée
✓ Annonce 6830a50acf58eeced2441add déjà traitée
✓ Annonce 692ad94d265523b710ed0dcd déjà traitée
✓ Annonce 6932dbdb8914daae519651bc déjà traitée
✓ Annonce 693c277a8914daae519a498e déjà traitée
✓ Annonce 693c26cccd04d08be749d444 déjà traitée
✓ Annonce 68b2e5a9711369bbe4f41e37 déjà traitée
✓ Annonce 68d1129807c7711d7c72b2b8 déjà traitée
✓ Annonce 691b5056265523b710e6a6b5 déjà traitée
✓ Annonce 693c18998914daae519a3fa5 déjà traitée
✓ Annonce 693c158fcd04d08be749c871 déjà traitée
✓ Annonce 693c1034cd04d08be749c4f4 déjà traitée
✓ Annonce 693c0f03cd04d08be749c433 déjà traitée
✓ Annonce 693c09c18914daae519a363d déjà traitée
✓ Annonce 693c0866cd04d08be749c052 déjà traitée
✓ Annonce 693c07cccd04d08be749c001 déjà traitée
✓ Annonce 6884c34c62d21a2c2e39b2d9 déjà traitée
✓ Annonce 693c05cfcd04d08be749bf0e déjà traitée
✓ Annonce 693c04cecd04d08be749be89 déjà traitée
✓ Annonce 693c02ca8914daae519a3225 déjà traitée
✓ Annonce 693bfe768914daae519a2fdf déjà traitée
✓ Annonce 693bfc8c8914daae519a2ec8 déjà traitée
✓ Annonce 693bfc638914daae519a2eb1 déjà traitée
✓ Annonce 693995d38914daae519931f4 déjà traitée
✓ Annonce 6932dceccd04d08be745d929 déjà traitée
✓ Annonce 693bf32f8914daae519a2952 déjà traitée
✓ Annonce 68dfa7396c505afdc05d3563 déjà traitée
✓ Annonce 693be7498914daae519a20ed déjà traitée
✓ Annonce 68d3b83ad39682ea75d68702 déjà traitée
✓ Annonce 691d97c7265523b710e78f40 déjà traitée
✓ Annonce 67f54e99ca3467b14e77fc55 déjà traitée
✓ Annonce 693be5458914daae519a1f57 déjà traitée
✓ Annonce 68c2e58fc4782c5427b108e0 déjà traitée
✓ Annonce 69398490cd04d08be748b13b déjà traitée
✓ Annonce 693be1778914daae519a1c88 déjà traitée
✓ Annonce 68cd640607c7711d7c707b6b déjà traitée
✓ Annonce 68f9f010b756576ab406c2fb déjà traitée
✓ Annonce 6888940662d21a2c2e3c4d60 déjà traitée
✓ Annonce 693bdb34cd04d08be749a380 déjà traitée
✓ Annonce 68dcf2cf516f1ddb82e75675 déjà traitée
✓ Annonce 68ff5610b756576ab409ab5a déjà traitée
✓ Annonce 68c1a122985e647fd0ec43cb déjà traitée
✓ Annonce 68fcc55bb756576ab4086556 déjà traitée
✓ Annonce 682c6c89e99ea7fe8b143aaf déjà traitée
✓ Annonce 693aae7ccd04d08be7492b63 déjà traitée
✓ Annonce 693bd605cd04d08be749a07f déjà traitée
✓ Annonce 68adae39032c2f2572190617 déjà traitée
✓ Annonce 68542e130e1c20e3eb0de9cc déjà traitée
✓ Annonce 693bce7c8914daae519a1175 déjà traitée
✓ Annonce 693bce6d8914daae519a116d déjà traitée
✓ Annonce 693bce6dcd04d08be7499c74 déjà traitée
✓ Annonce 693bce6ccd04d08be7499c73 déjà traitée
✓ Annonce 693bc8abcd04d08be74999dc déjà traitée
✓ Annonce 693bc8aa8914daae519a0ece déjà traitée
✓ Annonce 693bc8aacd04d08be74999db déjà traitée
✓ Annonce 693bc8078914daae519a0e80 déjà traitée
✓ Annonce 693bc8078914daae519a0e7e déjà traitée
✓ Annonce 693bc807cd04d08be749998c déjà traitée
✓ Annonce 693bc7828914daae519a0e4b déjà traitée
✓ Annonce 693bc7818914daae519a0e49 déjà traitée
✓ Annonce 693bc6ed8914daae519a0e02 déjà traitée
✓ Annonce 693bc6eccd04d08be7499928 déjà traitée
✓ Annonce 693bc6eccd04d08be7499927 déjà traitée
✓ Annonce 693bc6ebcd04d08be7499924 déjà traitée
✓ Annonce 693bc6eacd04d08be7499923 déjà traitée
✓ Annonce 68e78c723e7ffb8ac156f8db déjà traitée
✓ Annonce 68bfe86bc4782c5427af0bdc déjà traitée
✓ Annonce 691627c3145e1617cba5063b déjà traitée
✓ Annonce 68ce6b60516f1ddb82de9038 déjà traitée
✓ Annonce 68c53c3ce33e2deec9309a25 déjà traitée
✓ Annonce 68553494f0d1e1079c378684 déjà traitée
✓ Annonce 68fb3fbdb756576ab40785fc déjà traitée
✓ Annonce 693af8038914daae5199cab2 déjà traitée
✓ Annonce 693af433cd04d08be749535b déjà traitée
✓ Annonce 693af3b7cd04d08be7495325 déjà traitée
✓ Annonce 693af3a9cd04d08be749531e déjà traitée
✓ Annonce 68ffa29db756576ab409e0fb déjà traitée
✓ Annonce 6819ff14c1f8f57898eb7d22 déjà traitée
✓ Annonce 693ae65ecd04d08be7494c51 déjà traitée
✓ Annonce 693ae56fcd04d08be7494bab déjà traitée
✓ Annonce 693ae4458914daae5199c09b déjà traitée
✓ Annonce 693ae2cbcd04d08be7494a29 déjà traitée
✓ Annonce 68b87044711369bbe4f795f0 déjà traitée
✓ Annonce 68f20c47b756576ab4027531 déjà traitée
✓ Annonce 693adeabcd04d08be74947ae déjà traitée
✓ Annonce 693add728914daae5199bce8 déjà traitée
✓ Annonce 69247b77145e1617cbabb67a déjà traitée
✓ Annonce 6902070cd0d95991e1077f83 déjà traitée
✓ Annonce 692edf7f265523b710ee7e24 déjà traitée
✓ Annonce 6808c421c5beda2b51cdda65 déjà traitée
✓ Annonce 68e782493e7ffb8ac156ee6a déjà traitée
✓ Annonce 692f0b43265523b710ee99e5 déjà traitée
✓ Annonce 68b886d9df9d8936c1060ccf déjà traitée
✓ Annonce 693acd77cd04d08be7493d98 déjà traitée
✓ Annonce 693ac4778914daae5199ae0b déjà traitée
✓ Annonce 68fb7ccfd0d95991e1040988 déjà traitée
✓ Annonce 687b60f394cd0376dce2b4f3 déjà traitée
✓ Annonce 693ab7278914daae5199a66a déjà traitée
✓ Annonce 693ab70e8914daae5199a65a déjà traitée
✓ Annonce 693446f48914daae5196ea57 déjà traitée
✓ Annonce 692d8e39145e1617cbaec68e déjà traitée
✓ Annonce 693ab14f8914daae5199a33a déjà traitée
✓ Annonce 693ab040cd04d08be7492c71 déjà traitée
✓ Annonce 685c41f9d5464a896c9b3793 déjà traitée
✓ Annonce 68d920db07c7711d7c779d3b déjà traitée
✓ Annonce 690cb5998e4e0e4acb5e89c0 déjà traitée
✓ Annonce 690474fd8e4e0e4acb59fcd6 déjà traitée
✓ Annonce 68b70f20711369bbe4f6b3e4 déjà traitée
✓ Annonce 693a9d068914daae51999595 déjà traitée
✓ Annonce 673de6ab0d8480a1e0130d7c déjà traitée
✓ Annonce 68149a21c5beda2b51d5b2d0 déjà traitée
✓ Annonce 693a996bcd04d08be7491d79 déjà traitée
✓ Annonce 68e63b596c505afdc06109e7 déjà traitée
✓ Annonce 68c13f1bc4782c5427afe4cb déjà traitée
✓ Annonce 69295fa7265523b710ec82ca déjà traitée
✓ Annonce 693a8f52cd04d08be7491728 déjà traitée
✓ Annonce 693a8ebc8914daae51998ca6 déjà traitée
✓ Annonce 693a8dfacd04d08be7491655 déjà traitée
✓ Annonce 6932e18acd04d08be745dc0f déjà traitée
✓ Annonce 69282c76145e1617cbacecd9 déjà traitée
✓ Annonce 6921b5c3145e1617cbaa6768 déjà traitée
✓ Annonce 691332a9145e1617cba35fd5 déjà traitée
✓ Annonce 6873e01cd5464a896caafbee déjà traitée
✓ Annonce 692d51fd145e1617cbaea131 déjà traitée
✓ Annonce 69047d948e4e0e4acb5a03a9 déjà traitée
✓ Annonce 6904755c6490817594e037f7 déjà traitée
✓ Annonce 687b5f8ed5464a896cb06069 déjà traitée
✓ Annonce 692d5a11c4ff0a75f0e6d433 déjà traitée
✓ Annonce 693a8847cd04d08be749132f déjà traitée
✓ Annonce 68e1882c6c505afdc05e6824 déjà traitée
✓ Annonce 68db94d4516f1ddb82e6769d déjà traitée
✓ Annonce 68cd61d9516f1ddb82ddfaa9 déjà traitée
✓ Annonce 6872486494cd0376dcdc2d6f déjà traitée
✓ Annonce 69132b91145e1617cba35a7c déjà traitée
✓ Annonce 68f61c5ed0d95991e100fbdc déjà traitée
✓ Annonce 685125a58a733cfc286c8844 déjà traitée
✓ Annonce 682f2bbc6238a0abfdd52372 déjà traitée
✓ Annonce 693a809bcd04d08be7490f66 déjà traitée
✓ Annonce 693a7ed18914daae51998464 déjà traitée
✓ Annonce 692488377659bc83a27548e1 déjà traitée
✓ Annonce 69248c8c265523b710eae728 déjà traitée
✓ Annonce 69394315cd04d08be7488884 déjà traitée
✓ Annonce 68e3d7f06c505afdc05fa26b déjà traitée
✓ Annonce 6869031894cd0376dcd5e954 déjà traitée
✓ Annonce 67f63f5bca3467b14e788b6b déjà traitée
✓ Annonce 68e61c876c505afdc060eeaa déjà traitée
✓ Annonce 6939ee18cd04d08be748ef78 déjà traitée
✓ Annonce 6939e6dbcd04d08be748ec05 déjà traitée
✓ Annonce 6904b7328e4e0e4acb5a332b déjà traitée
✓ Annonce 6852c3068a733cfc286db3aa déjà traitée
✓ Annonce 6912166a145e1617cba2b9c2 déjà traitée
✓ Annonce 6939ac368914daae51993eb0 déjà traitée
✓ Annonce 6939a6fb8914daae51993b69 déjà traitée
✓ Annonce 692ae341145e1617cbade922 déjà traitée
✓ Annonce 68fcef11d0d95991e104d560 déjà traitée
✓ Annonce 69399f378914daae5199374a déjà traitée
✓ Annonce 673de4f20d8480a1e0130b8a déjà traitée
✓ Annonce 69023258d0d95991e107a186 déjà traitée
✓ Annonce 693985078914daae5199283d déjà traitée
✓ Annonce 693982ac8914daae519926c5 déjà traitée
✓ Annonce 68e142fee7035d31a40f3feb déjà traitée
✓ Annonce 68542a1a0e1c20e3eb0de614 déjà traitée
✓ Annonce 679dfa2fa487ea2259c2e2de déjà traitée
✓ Annonce 69397f4b8914daae5199246e déjà traitée
✓ Annonce 69397b578914daae519921fe déjà traitée
✓ Annonce 69397316cd04d08be748a666 déjà traitée
✓ Annonce 6939671bcd04d08be7489f42 déjà traitée
✓ Annonce 6921c727265523b710e999eb déjà traitée
✓ Annonce 685574ff94cd0376dcc99239 déjà traitée
✓ Annonce 68d7bf8a516f1ddb82e45438 déjà traitée
✓ Annonce 68d7bc5d07c7711d7c76d469 déjà traitée
✓ Annonce 69395129cd04d08be748923b déjà traitée
✓ Annonce 692d90ad265523b710edf208 déjà traitée
✓ Annonce 68ed071c53fa6375757b8142 déjà traitée
✓ Annonce 69208550265523b710e914c9 déjà traitée
✓ Annonce 692717c1145e1617cbac95dc déjà traitée
✓ Annonce 69385aab8f2e14782652c1ce déjà traitée
✓ Annonce 68e62e0ee7035d31a412099b déjà traitée
✓ Annonce 684816d492753d6d79ad296c déjà traitée
✓ Annonce 68ed0c613e7ffb8ac15a0dad déjà traitée
✓ Annonce 68d25b32516f1ddb82e10694 déjà traitée
✓ Annonce 6939420e8914daae5198ff62 déjà traitée
✓ Annonce 68ed07a3ebd8d75bc802a280 déjà traitée
✓ Annonce 6915f595145e1617cba4e2e5 déjà traitée
✓ Annonce 68fa0b74b756576ab406db3b déjà traitée
✓ Annonce 689dd62aabdbeff489cc048c déjà traitée
✓ Annonce 692eb143265523b710ee5f4d déjà traitée
✓ Annonce 691c9107145e1617cba7fa6e déjà traitée
✓ Annonce 69393c56cd04d08be74883a9 déjà traitée
✓ Annonce 693939d98914daae5198f9fe déjà traitée
✓ Annonce 685e806194cd0376dcced3a8 déjà traitée
✓ Annonce 683acbe1a2a7af1206232208 déjà traitée
✓ Annonce 68f606afb756576ab40497d5 déjà traitée
✓ Annonce 681f0fcfa9299683d0a92802 déjà traitée
✓ Annonce 68dce5fd516f1ddb82e74a5f déjà traitée
✓ Annonce 6793c9f76286c24145752ef8 déjà traitée
✓ Annonce 690c6c066490817594e48d54 déjà traitée
✓ Annonce 67d7017dca3467b14e65f602 déjà traitée
✓ Annonce 67bc597baf2813f80759103c déjà traitée
✓ Annonce 68dcf140516f1ddb82e7550b déjà traitée
✓ Annonce 68ff8f26b756576ab409d1aa déjà traitée
✓ Annonce 688c86924ad00efe973520cc déjà traitée
✓ Annonce 68de38a5e7035d31a40d882b déjà traitée
✓ Annonce 69392d368914daae5198f2cb déjà traitée
✓ Annonce 69392d0ecd04d08be7487a8f déjà traitée
✓ Annonce 693400cf8914daae5196c568 déjà traitée

[]

In [17]:
import pandas as pd
import json

# Load your JSON file
with open("extracted_features_raw_data.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

# If your JSON is {id1: {...}, id2: {...}, ...}
# Convert dictionary to list of records
if isinstance(data, dict):
    records = list(data.values())
else:
    records = data  # If it's already a list

# Convert to DataFrame
df_results = pd.DataFrame(records)

# Set 'id' as index if you want
# df_results.set_index('id', inplace=True)

print(f"DataFrame shape: {df_results.shape}")
print(f"Columns: {df_results.columns.tolist()}")
df_results.head()

DataFrame shape: (2502, 16)
Columns: ['id', 'texte', 'surface', 'nombre_des_chambres', 'nombre_des_salles_de_bains', 'haut_standing', 'terrasse', 'balcon', 'etage', 'parking', 'ascenseur', 'jardin', 'vue_panoramique', 'climatiseur', 'chauffage_central', 'piscine']

,id,texte,surface,nombre_des_chambres,nombre_des_salles_de_bains,haut_standing,terrasse,balcon,etage,parking,ascenseur,jardin,vue_panoramique,climatiseur,chauffage_central,piscine
0,693c50e8cd04d08be749ee7a,"Appartement S+2 sur la route du Relais, dans ...",0.0,2,1,False,False,True,0,False,False,False,False,True,True,False
1,693ef21fcd04d08be74add4e,Je mets en vente cette appartement s+2 90 m2\n...,90.0,2,0,False,False,False,0,False,False,False,False,False,False,False
2,692b30e3145e1617cbae0a19,À VENDRE – Bel appartement S+2 proche de la pl...,0.0,2,1,True,False,False,2,False,False,False,False,True,True,False
3,68ced66b516f1ddb82deec8b,immobilière ajina vous propose :\n\nÀ VENDRE –...,0.0,2,0,False,False,False,2,False,False,False,True,True,True,False
4,6835f44f1539f905891f465b,A vendre des appartements Haut standing en co...,0.0,2,0,True,False,False,0,False,False,False,False,False,False,False

In [19]:
len(df_results[df_results.surface==0])

2409